### ISSUE TITLE
iOS > Onboarding > Landing Screen

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#109]
**Narrative**: 
As a user, when I launch Amplica Connect, I would like to see a landing page, so that I can see and overview of what Amplica Connect is and how to get started. 

**Overview**: 
This story is to build out the landing page screen. 

Figma Link: 
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773%3A12492&t=RYddAnIVbqcZg3Ku-1

**Requirements**: 
* Screen design and styling should match Figma spec. 
* User should see 3 buttons: Create Identity, I have an Social Identity, Restore from Backup
* User should see a footer with text link buttons for Terms and Privacy Policy.  *Link destination TBD

**Comment by VitaliKrasnik** [comment]
Here are the minor inconsistencies 

1. “Backup” is written in lowercase (button "Restore from Backup" )
2. There is no spacing between the "Restore from Backup" button and 
                              the footer 
3. The words "Terms and Privacy Policy" are displayed in blue, 
                               but they should be orange according to the Figma design.

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/e0ecf5a3-6abe-433a-a2c0-db1b33a42464)

**Comment by VitaliKrasnik** [comment]
We shouldn’t support the landscape mode

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/f7ced248-a16c-4dbf-ac37-04242e3e6d4d)
