### ISSUE TITLE
iOS > Onboarding Screens > Create Identity - Claim Handle Screen 

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#111]
**Narrative**: 
As a user, I can create a user handle for my social identity, so that I can be discoverable on the social web

**Overview**: 
This story is to build the "Claim Handle" screen. When a user chooses to create an identity in the Amplica Connect app, we want to provide them the option to create a user handle. 

Figma Link: 
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773%3A11939&t=qt3iToXLOMEzLphz-1

**Requirements**: 
* Tapping on "Create Social Identity" in the app "Landing screen" should direct user to the "Claim Handle" screen. 
* Tapping / pressing "Back" button should return user to app "Landing Screen" 
* Screen design and copy should match what is displayed in Figma
* Tapping on SKIP button should let user skip the handle creation and proceed to the "Create ID Success" screen. 
* Auto select text field and show keyboard on entry to "Claim Handle" screen. 
* Handle should be 16 characters max since this is what MeWe supports today. 
* Once minimum character requirements are met, then "Next" button should become tappable. 
* Tapping on the "Next" button should direct user to the Confirm handle screen. Handle suffix should be displayed. 
* Handle length should be 4-16 characters

**Comment by VitaliKrasnik** [comment]
1 of 3 Page Issues: 

1. The next button should be disabled by default (greyed out) until 4 characters is entered
2. Skip for now the link is not working ()
3. When the 1 of 3 page is opened the focus should be defaulted on the input field and the keyboard should be visible 
4. What is the maximum number of characters for a handle, according to the message on the screen it should be 16. Should we set a limit for that? 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/0ad92282-2888-47f4-81eb-4516e4c0b919)
2 of 3 Page Issues: 

1. The text is not fully visible 
2. Add more space and make the Font Bold  in “Confirm your Handle”
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/4a9b5523-502e-4c2a-a9ab-4dedb08ccdb8)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/7355411e-f50b-424c-86f7-b4c07660db80)

3 of 3 Page Issues: 

Alignment (Please check the figma design )

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/5bb8de3b-3b80-41ef-a65c-dfa74f849f81)

**Comment by BenJamminnn** [comment]
alright, so I fixed the issues outlined. The only thing is where should "skip" navigate to?
