### ISSUE TITLE
iOS > Onboarding Screens > Create Identity - Agree to Terms Screen

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#112]
**Narrative:** 
As a user, I would like to see what permissions Amplica Connect is asking for, so that I'm aware of what info I'm agreeing to share. 

**Overview:** 
This story is to create the Agree to Terms screen. The goal of this screen is to show the user what permissions are being requested from the provider. Permissions can vary based on capabilities of the app.  

**Figma Link**
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773%3A11981&t=dxsqzZUGxb6v2RLs-1

**Requirements**
* Design and UI should match figma comp 
* Display permissions being requested. These permissions will be based on schema id.  *Note* API is still TBD so we should stub this for now. 
* Show "Agree" button. When button is tapped, user should be directed to the identity screen with "Congratulations" banner displayed. 
* Footer should be displayed with link buttons that go to: Terms, Privacy Policy and Learn More.  *Note* Link destinations are still TBD.

**Comment by VitaliKrasnik** [comment]
Tested, works as expected
