### ISSUE TITLE
iOS > Onboarding Screens > Create Identity - Congratulations Banner 

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#113]
**Narrative:** 
As a user, once I create my social identity, I would like to see a banner that let's me know the process is complete and what I should do next. 

**Overview:** 
This story is to build a banner that let's the user know they have completed the initial social identity creation. The goal of the banner is to inform the user that their social identity was created and what they can do next. 

**Figma Link**
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773%3A11939&t=dxsqzZUGxb6v2RLs-1

**Requirements**
* Create banner UI and copy as defined in figma spec. 
* Banner should contain a close button. If tapped, the banner should be dismissed. 
* Create a button "Finish Digital Identity". Tapping the button should direct user to the profile screen where they can fill out additional profile information. 
* Create a text button link for "Skip". Tapping this button should dismiss the banner.

**Comment by VitaliKrasnik** [comment]
Congratulations main text should have a center alignment 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/62fa157a-48ad-4590-96b5-7789a8430a41)

**Comment by VitaliKrasnik** [comment]
Now it's working as expected
