### ISSUE TITLE
iOS > Seed Phrase Flow Updates

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#118]
**Narrative:** 
As a user, I would like to see my seed phrase at my convenience, so that I can ensure I have it written down and backed up securely. 

**Overview:** 
This story is for creating and updating the seed phrase flow. 

**Figma Link**
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4771%3A11318&t=eZRNVwwXBVnIno6s-1

**Requirements**
* Create bottom bar button labeled "Settings" 
* Tapping on Settings bottom bar button should display Settings screen with "Reveal Recovery Phrase" button. 
* Tapping on "Reveal Recovery Phrase" button should direct user to the "There will be a test" flow. 
* Display a "Back" button that allows the user to return to the Settings screen when. tapped. 
* If user enters incorrect seed phrase, reset the puzzle and show message toast indicating there was an error "The recovery phrase you entered is incorrect. Please try again."
* If user enters the correct seed phrase. Show message "Congratulations!" and direct user back to the Settings screen with "Complete" message.
* Update the flow to match figma designs.

**Comment by VitaliKrasnik** [comment]
Issues found: 

1. Screenshot 1 - 
The Page header should be: Security is important 

2. Screenshot 2 - 
Incorrect Padding for long words 

3. Screenshot 3
The error message doesn’t match to the requirements.
Expected : The recovery phrase you entered is incorrect. Please try again.
Actual: You got the test Wrong. 


4. The error message is not displayed after mnemonic phrase is entered incorrectly for the 2nd time
Steps to reproduce: 
 Enter the mnemonic phrase in an incorrect order and press continue button
Click on Ok button on pop-up modal window
Enter the mnemonic phrase in an incorrect order again 
Expected result: Error message is shown 
Actual Result: Error message is not show

5. The Success message is not displayed after the mnemonic phrase was entered incorrectly. 

Steps to reproduce: 
1. Enter the mnemonic phrase in an incorrect order and press continue button
2. Click on Ok button on pop-up modal window
3. Enter the mnemonic phrase correctly
Expected result: A success message is shown 
Actual Result: The message is not shown

6. As we discussed during the meeting the seedphrase should be reset if the user enters the incorrect order for the mnemonic phrase



![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/d3183f91-ea1b-460f-ac35-60e37a622b99)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/1bbaaca7-3242-4fd3-85c6-6cb2972cc5cf)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/532ce9cf-da48-4c8f-a50e-9900ff3dcb43)

**Comment by VitaliKrasnik** [comment]
It looks good
