### ISSUE TITLE
iOS > Onboarding Full Flow

### ISSUE THREAD

**Issue by ryansheh** [LibertyDSNP/dsnp-wallet-swift#125]
On release schema, start to end just go through entire onboarding flow.
(Piecing everything together)

Including, but not limited to:
1) Generating keys/mnemonic behind the scenes for user 
2) Saving keys/mnemonic for reference later
3) Kicking user to Home Screen

**Comment by VitaliKrasnik** [comment]
Tested Build: 10 on the app center.
