### ISSUE TITLE
iOS > QA Scheme + Requests

### ISSUE THREAD

**Issue by ryansheh** [LibertyDSNP/dsnp-wallet-swift#129]
[Description]
As a QA, I would like to have a control panel for various debug options and features

Create a debug menu that contains : Navigate (Contains all pages ), Frequency Chain (Allows to manipulate the chain), Feature flags 

1) **QA Scheme** - Create a QA scheme so that we can inject QA specific logic with a corresponding config.
2) **Landing Screen** - Update landing screen of QA scheme to the same landing screen as release (aka start of onboarding)
3) **Btn on Config** - Create a btn that only shows with the QA config btn
4) **Consolidate Test/QA VC** - Consolidate testVC below qaVC's node address bar, and have the btn you created nav to this screen.

* In particular, I would like to include a feature flag within this menu to enable or disable the Accepting Terms and Conditions pop-up. By default, this feature should be turned off in the development build. 
* The purpose of this flag is to prevent the Terms and Conditions pop-up from appearing before each tap on the button during testing.

**Comment by ryansheh** [comment]
@VitaliKrasnik , please add any further details/requests you'd like to this story.

**Comment by VitaliKrasnik** [comment]
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/471e0dde-e864-4b27-9d65-0a6f0eed81ec)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/df221e35-225e-4d5d-aa36-b8a90a5314d0)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/e9cd45aa-08ca-4ac8-8b5e-14d46997762c)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/6f964718-0bb8-4959-968a-2e653c6416b7)
