### ISSUE TITLE
iOS > Settings Screen

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-swift#134]
**Narrative:** 
As a user, I would like to have a settings screen, so that I can easily manage and customize app settings at a global level.

**Overview:** 
This story is to create a "Settings" screen that will be the home for global app settings. 

**Figma Link**
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773%3A12167&t=3oH44KiiO79G28uG-1

**Requirements**
* Screen design and layout should match what is displayed in figma doc. Link above. 
* In order to access the Settings screen, a "Settings" button should be displayed in the bottom tab bar. Label "Settings" 
* Screen heading label "Settings" 
* Copy should match what is in the figma doc. Link above
* Button "Reveal Recovery Phrase" should be displayed. Tapping on button should direct user to the "There will be a test" flow. 
* FaceID, TouchID section should be displayed. Create a toggle that allows user to turn biometrics  ON/OFF  *Functionality for this will be part of another story. This is just showing the section / toggle in the Settings screen .

**Comment by VitaliKrasnik** [comment]
Make sure the toggle header is changing depending on the device type. 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/33b18c56-3c6e-4594-9dd9-988a8d0df916)

**Comment by VitaliKrasnik** [comment]
Also please add the new logout button 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/e6c4a8b8-fc94-4260-856a-95c95cbf5806)

**Comment by VitaliKrasnik** [comment]
Fixed, the Face ID button will be replaced with
