### ISSUE TITLE
iOS > Identity Screen

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-swift#139]
**Narrative**:
As a user,  I would like to see a social identity screen in Amplica Access Pro, so that I can view and manage my social identity whenever I want. 

**Overview**: 
This story is to support building out an social identity screen. This screen will allow users to see their social identity (user handle) and over time evolve to include more metadata options that will serve as a "control center" for users to edit as they see fit. 

**Resource Link**: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A2031&t=BvxZCzC2Cr5rnHfT-1

**Requirements**: 
* Design screen to match what is displayed in figma comps
* Show static default profile pic as shown in figma *Note that avatar support will be a separate story. 
* Show user handle below default profile pic. Full handle should be displayed user handle+suffix 
* Show "Social Identity Complete" progress section. Include progress meter and step 1/x to complete. As user completes  profile setup steps, the progress meter should update. 
* Show "See All" button text link that directs user to Social Identity Progress screen. 
* "Frequency token banner" should NOT be displayed in MVP. *QA Note: , note that I added this requirement after Ben worked on the story and he's going to remove in another PR

**Comment by VitaliKrasnik** [comment]
The user handle is not shown below the default profile picture. 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/ea45779b-763f-4750-8362-a96b094784d0)

**Comment by BenJamminnn** [comment]
@VitaliKrasnik  This problem occurs only in the Debug environment. Please check the release build if you can. The reasoning is, that the handle is established in the previous step. In this scenario, the handle is never established

Edit: I was able to get to this point using the sign in flow in debug, do you have steps to reproduce the issue? I wasn't able to

**Comment by VitaliKrasnik** [comment]
Resolved 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/888d1fee-d9d2-4237-9dfe-85dfa98e9bab)
