### ISSUE TITLE
iOS > Social Identity: Progress Screen

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-swift#140]
**Narrative**:
As a user, I would like to see suggested steps for updating my social identity, so that I can get the most out of my social web experience. 

**Overview** 
This story is to create the Social Identity: Progress Screen. This screen is designed to highlight key features that are important so users get the most out of their experience on the social web. The screen will contain a list of tasks for users to complete. After completing the task, a check will be displayed next to it to indicate completion. 

Resource Link: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A2133&t=BvxZCzC2Cr5rnHfT-1

**Requirements**: 
* Design of screen should match Figma comp
* Show header "Social Identity" 
* Show "Back" button. Tapping button should direct the user back to the social identity screen. 
* Show "Social Identity Progress" indicator with steps needed to complete i.e. 1/x. Completing a step should update the progress meter and step count. 
* Show copy that is displayed in figma *Note: this is not final and will be updated later under another story. 
* Show Step buttons. If step has been completed; show as visually indicated in figma with green check mark. 
* If task is NOT complete, show as visually indicated in Figma comp. 
* Show tasks: Backup Recovery Phrase, Choose Handle *Note that for MVP, almost all users will have a user handle and since we are only focused on migration of existing users (custodial to non-custodial) this will be more than likely be checked for these users.

**Comment by VitaliKrasnik** [comment]
Functional bug

Updated: Bug was moved to this ticket 
https://app.zenhub.com/workspaces/mobile-dev-63bd9fc94c79400014094c80/issues/zh/83

Screenshot 1
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/8b1ea1e6-3498-47d6-b97f-722499bbc86b)

Screenshot 2 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/41c5e4ec-3785-4896-8b27-7b81571b8705)

**Comment by VitaliKrasnik** [comment]
User is not able to enter Underscores

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/643918ad-e5f4-400c-9367-f0bc5d95c14c)

**Comment by VitaliKrasnik** [comment]
The tappable area needs to be increased, as for now user have to tap on the icon itself 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/46599483-1e59-4ec2-9253-27292ff12686)

**Comment by VitaliKrasnik** [comment]
Also please restrict the input of more than 16 characters 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/afc98e3f-be12-4986-9f1e-f9e91c6d36a7)

**Comment by VitaliKrasnik** [comment]
The issues above are resolved
