### ISSUE TITLE
iOS > Restore Wallet Flow

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-swift#142]
**Narrative:** 
As a user, I would like to be able to restore my wallet using my secret recovery phrase, so that I can easily recover my data 

**Overview:** 
This story is to implement the Restore Wallet flow. Upon successfully entering their 12 word recovery phrase, the user should be able to recover their MSA, user handle and associated keys. 

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A10667&t=TWTsARJcVqiqZ2Az-1

**Requirements**
* User should see text button link on the landing screen labeled "Restore Account" 
* Tapping on the "Restore Acount" text button link should direct the user to the "Import Account" screen. 
* Screen and copy should appear as it does in figma link. 
* Upon page entry, description text as shown in figma should be displayed. Tapping into the text box should clear text and show cursor and auto launch keyboard. 
* User should be able type in their recovery phrase 
* User should be able to paste in their recovery phrase 
* Connect button should not be selectable until 12 words have been entered into text box. 
* Each word should be separated by a space. 
* If user enters the incorrect recovery phrase, show error messaging as shown in figma
* Tapping "Try Again" should clear word list and allow user to begin from the start.
* Upon successful entry of recovery phrase, user should be directed to the Identity screen

**Comment by VitaliKrasnik** [comment]
Connect button becomes enabled after 11 words are entered and 1 extra space, but expected it becomes enabled after 12 words  
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/885f5b4c-ec75-4368-84ed-8d516d83cb99)

**Comment by VitaliKrasnik** [comment]
Upon page entry, description text as shown in figma should be displayed. Tapping into the text box should clear text and show the cursor and auto launch keyboard.

Expected: 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/bbccd66f-8313-4294-9af7-5f0de1308814)

Actual:
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/9dda6623-63f1-4540-a6e9-683f035b71e9)

**Comment by VitaliKrasnik** [comment]
By design the try again button should be a bit bigger than the create identity one
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/3193f701-075e-4827-af7c-c81792e3d3dd)

Design 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/814b37df-cbcf-4825-95be-3b4a8b9e32e5)
