### ISSUE TITLE
iOS > Create ID Screen > Remove "Skip for Now" button link & text

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-swift#158]
**Overview**: 
Please remove the "Skip for Now" button from the Create ID screen. 

**Link**: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1549&mode=design&t=2tZlRCr6pv7cUGit-1

**Comment by VitaliKrasnik** [comment]
Tested: App Center Build: 10
