### ISSUE TITLE
iOS > Settings Screen > Logout > "Are You Sure" alert

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-swift#164]
**Narrative:** 
As a user, when I tap the Log Out button, I would like to see a popup that confirms my choice and reminds me about the importance of backing up my recovery phrase, so that I am aware of the risk and have a chance to double check that I backed up my recovery phrase. 

**Overview:** 
When a user taps on Log Out button (located in the Settings screen), we want to show an "Are You Sure" alert that reminds the user about the importance of backing up their recovery phrase. 

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=515%3A12579&mode=design&t=74A6IsHCFuCrRS6f-1

**Requirements**
* When user taps the "Log Out" button located in the Settings screen, show an alert as it appears in figma. 
* Tapping "View Recovery Phrase" should direct the user to the Backup Phrase screen. 
* Tapping Log Out should delete the users wallet account and associated keys.

**Comment by VitaliKrasnik** [comment]
Tested: Appcenter build 10
