### ISSUE TITLE
SPIKE > Storing Keys

### ISSUE THREAD

**Issue by ryansheh** [LibertyDSNP/dsnp-wallet-swift#36]
**Overview:** 
Explore specific ways to secure keys on both platforms, while still providing a mechanism (or preferably mechanisms) to back them up.

Is this things like iCloud drive, or password managers (including but beyond iCloud keychain), or drive solutions like dropbox, etc.

**Requirements:** 
- Recommended way to store the keys. 
- Maybe there isn’t one clear winner but will allow us to compare
- Given way we are storing keys what is the best way to backup, recover and transfer.

**Comment by ryansheh** [comment]
The Secure Enclave Processor lives separately from the operating system and cannot be accessed with any kernel attacks. It serves as a blackbox that only gives confirmation to sensitive auth information like biometrics, or your Apply Pay information, and seems to be the safest way to save data on the iPhone. 

Though it's capable of generating keys, they cannot generate blockchain keys. Blockchain keys are symmetric, elliptical curve encrypted, while the keys in Secure Enclave are required to be asymmetric. And even if it could generate our keys, they would not be exportable due to its black box design. So it seems Secure Enclave is off-the-table.

The wallets that do claim to use Secure Enclave, don't do so in the way mentioned above, but through the carefully worded "keychain backed by Secure Enclave". Fearless, Nova (derived from Fearless), Bread Wallet (BRD) and Parity Signer store their keys this way. That means if anything were to happen to the keychain data, which Apple previously relied on to hold sensitive data, the key required to decrypt it lives in Secure Enclave. This seems to be the mostly widely spread methodology for handling keys on iOS as far as I know. 

The final interesting project was related to Rigo's research in this matter, VivoPay, which also boasted utilizing Secure Enclave. However, they reveal one feature of Secure Enclave, which is encrypting the mnemonic directly into Secure Enclave. When private keys are needed, they derive the keys from the mnemonic and the public key, sign whatever needs to be signed, and then delete everything from memory. Grabbing data from Secure Enclave is more timely and operation intensive, but not noticeably-so and a fair trade-off for the price of security. I believe Vivopay chose to save the mnemonic and derive private keys, instead of saving private keys as strings in the same way, to reduce the amount of data is accessible/managed. The only limitation that I could find with this is that the encryption required for the string to be stored into SE is strictly `eciesEncryptionCofactorVariableIVX963SHA256AESGCM`, which doesn't seem to be an issue at all.

Documentation regarding Secure Enclave is not robust, and mostly speculated, so perhaps technically, the encryption of a mnemonic into Secure Enclave is not that different from relying on a key in Secure Enclave to decrypt data off keychain. The wide spread reliance on keychain seems to prove that it's reliable, but if I had to lean on a methodology, perhaps Vivopay is most ideal, though I'm not sure.

**Comment by DannyAhmedApex** [comment]
My research findings on a nova are that nova is using Keystore to generate private keys and public to protect the secure key. Secure key is generated through KeyGenerator and encrypted with Keystore public key then converted into base64 encoded string at the end it stored on shared preferences. Any account added to nova wallet has secret info which consists of keypairs (public/private key), derivation path, etc. Secret info is protected by a secret key and the secret key is protected by the Keystore public/private key.

If the Keystore doesn't have any key then we create a new one and the Keystore keeps that key. The same is for the secure key. If it doesn't exist then create a new one with KeyGenerator class.

The encryption is happening on two levels first protected secure key and the second protected info with a secret key. Keystore is an independent source which doesn't dependent on OS if the OS is compromised or the device is rooted then it doesn't have any effect on KeyStore it will be safe.

Below is more info from its official documents.

Android Keystore system protects key material from unauthorized use. Firstly, Android Keystore mitigates unauthorized use of key material outside of the Android device by preventing extraction of the key material from application processes and from the Android device as a whole. Secondly, Android KeyStore mitigates unauthorized use of key material on the Android device by making apps specify authorized uses of their keys and then enforcing these restrictions outside of the apps' processes.

Extraction prevention
Key material of Android Keystore keys is protected from extraction using two security measures:

Key material never enters the application process. When an application performs cryptographic operations using an Android Keystore key, behind the scenes plaintext, ciphertext, and messages to be signed or verified are fed to a system process which carries out the cryptographic operations. If the app's process is compromised, the attacker may be able to use the app's keys but cannot extract their key material (for example, to be used outside of the Android device).
Key material may be bound to the secure hardware (e.g., Trusted Execution Environment (TEE), Secure Element (SE)) of the Android device. When this feature is enabled for a key, its key material is never exposed outside of secure hardware. If the Android OS is compromised or an attacker can read the device's internal storage, the attacker may be able to use any app's Android Keystore keys on the Android device, but not extract them from the device. This feature is enabled only if the device's secure hardware supports the particular combination of key algorithm, block modes, padding schemes, and digests with which the key is authorized to be used. To check whether the feature is enabled for a key, obtain a KeyInfo for the key and inspect the return value of KeyInfo.isInsideSecurityHardware().

More info: https://developer.android.com/training/articles/keystore#GeneratingANewSecretKey

Summary:

![Image](https://user-images.githubusercontent.com/108344795/191528077-9c85ff1d-a44a-49bc-a384-724c0213dce7.png)
