### ISSUE TITLE
User can backup keys to cloud (iCloud, Google Drive, Dropbox, 1Password)

### ISSUE THREAD

**Issue by ryansheh** [LibertyDSNP/dsnp-wallet-swift#38]

**Comment by DannyAhmedApex** [comment]
As per my finding on Google Drive, Dropbox has the support of SDK for mobile apps so we can utilize the SDK to interact with Google Drive and Dropbox.

How we process:

First, our key must be encrypted with our public key so then we can decrypt it with our private key, encrypted key can pass through SDK to Dropbox or Google drive to store in a file. We can access the encrypted key through SDK whenever we made a call, so then we can decrypt with our private key which can either be stored on the device If not then we can recall it from our server

I have checked the docs about 1password so I could not find any SDK or API to pass info to 1password in that case either we manually store info or drop it
