### ISSUE TITLE
iOS > Existing DSNP ID Flow > Lookup By Email

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#45]
**Narrative** 
As a user, I would like to be able to lookup by DSNP ID (with my MeWe email address), so that I can easily migrate my account to the standalone wallet. 

 **Overview** 
This story is to build out the DSNP lookup by email flow. 

**Figma Link:** 
https://www.figma.com/file/JacuBzETlFr0VNjBQKKRgi/Wallet-Concepts?node-id=1161%3A3038&t=GxoyoBgW8ek8Y4Rw-1

 **Requirements**
- Screen designs should appear as they do in Figma *link below 
- On entry to DSNP ID lookup screen, the text field should be auto selected and keyboard should be visible. Alphabetical keyboard should be used
- Valid email address should be required for Send Auth Code button to highlight 
- Tapping on Restore DSNP Wallet should direct user to "Enter Seedphrase" screen 
- Use same placeholder Terms and Privacy Policy links that were used in the Welcome page. 
- Once valid email has been submitted the "Enter Code" screen should be displayed. 
- If  auth code entered is valid, proceed to seedphrase creation flow. 
- If auth code entered is not valid, show error state

**Comment by ryansheh** [comment]
Validating Phone and email, and code validation (using 3rd party service "Magic") contingent on discussion with SAAS.
