### ISSUE TITLE
iOS > Existing DSNP ID Flow > Lookup by Phone Number

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#46]
**Narrative** 
As a user, I can lookup by DSNP ID by phone number, so that I can begin setting up my DSNP profile in the wallet. 
 

**Overview** 
This story is to create the screens for users to lookup their DSNP ID by country code / phone number. After entering a valid phone number the user should receive an auth code via text that they can enter in order to confirm they are the owner of the account. 

Figma Link: 
https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773-12250&t=Tc0gsijGcW0mIQ12-0

 **Requirements**
- DSNP ID > Lookup by Phone Number flow should match Figma designs. 
- User can toggle to Phone number entry flow
- Numerical keyboard should be default when Phone Number flow is selected and field should be auto selected so that user does not have to tap. 
- User should have option to choose country code. For now we can default to USA +1 but we may choose another default at a later time. 
- Tapping on Country code should open the Country Code selection modal. Country name and code should be displayed. *Nice to have country flag but we can add another story if development prefers. 
- On country code selection, modal should close and code should be auto populated. 
- User can type phone number into Phone Number field. Error messaging should be displayed as defined in Figma
- Upon successful country code and phone number entry the user should be sent an SMS message containing the country code and the Auth Code entry screen should be displayed. 
- If auth code is valid, user should be directed to the create seedphrase flow. 
- If auth code is invalid, user should see error message as defined in Figma

**Comment by ryansheh** [comment]
Work completed in #45 without country code. Country code logic can be implemented at a later time when theming/verbiage is finalized.

**Comment by BenJamminnn** [comment]
@crbnlng the figma link isn't working anymore

**Comment by VitaliKrasnik** [comment]
@BenJamminnn  https://www.figma.com/file/VsQgst2fNunFslqEWdnjfV/Wallet-Concepts---Locked?type=design&node-id=4773-12250&t=Tc0gsijGcW0mIQ12-0
