### ISSUE TITLE
iOS > Create and Confirm Seed Phrase Flow

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-swift#47]
**Narrative** 
As a user, I would like to understand the importance of backing up my seed phrase, so that I am in control of my data and can restore my wallet at a later time. 

 **Overview** 
Users will need to generate and confirm a seed phrase in order to take control of their DSNP ID profile. This story is to create the generation and confirm flow. 

Figma Link: 
https://www.figma.com/file/JacuBzETlFr0VNjBQKKRgi/Wallet-Concepts?node-id=1161%3A3038&t=GxoyoBgW8ek8Y4Rw-1

 **Requirements**
- Seed Phrase screens should match Figma designs 
- Standalone wallet app should be able to generate a 12 word seed phrase. 
- After seed phrase is generated and user taps "I've written it down" button, an alert should be displayed informing user that they will not be able to access the seed phrase once they continue. 
- Tapping "Check again" should return user to the seed phrase screen. Seed phrase should be the same and should not change if a user selects "Check again" 
- If user selects YES, then display "This is a Test" screen where they can confirm the seed phrase. 
- Tapping on word should input the word into the numbered boxes in ascending order. If user makes a mistake, they can tap on the word in the numbered box and it will return to the bottom selection list. 
- If seed phrase is entered incorrectly, error messaging should be displayed *see Figma
- If seed phrase is entered correctly then proceed to create device pin code flow

**Comment by ryansheh** [comment]
Not utilizing real seed phrases until we implement generating real accounts. In the meantime, just using the alphabet.

**Comment by VitaliKrasnik** [comment]
According to the design, we should use vertical order for the cells 

![Image](https://user-images.githubusercontent.com/21163633/217041301-84e47a68-18bc-443a-92e2-75961f17b0e6.png)
