### ISSUE TITLE
IOS > DSNP wallet can't be built for iOS Simulator that's running on arm64 (Apple Chip)

### ISSUE THREAD

**Issue by VitaliKrasnik** [LibertyDSNP/dsnp-wallet-swift#67]
DSNP wallet can't be built for iOS Simulator that's running on arm64 (Apple Chip)
The problem is located in the SubstrateSdk pod which doesn't support arm64 architecture. 

In order to make it built for x86_64 (Intel) simulators, the  arm architecture should be excluded from the project build settings as it is shown in the screenshot below, 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/185fd701-9a14-4825-9e05-9c64fee7e017)

**Comment by BenJamminnn** [comment]
## Installation

M1 Macs:

There is a known issue regarding some crypto related dependencies not running on Apple Silicon Machines. There is a workaround using Rosetta.

Navigate to your machine's Applications folder, right click Xcode, select Get Info. Select "Open with Rosetta". Quit and restart Xcode, and the project should run as in Intel based Mac would 

![rosettaInfo.png](https://images.zenhubusercontent.com/644a9c59904fc28182fdabd1/d76c0995-665a-4f43-973d-a932b6fa8a9a)

**Comment by BenJamminnn** [comment]
If you don't have rosetta installed, simply run 
`softwareupdate --install-rosetta`
