### ISSUE TITLE
addPublicKeyToMsa function from ExtrinsicManager returns 'unknown' result during execution

### ISSUE THREAD

**Issue by VitaliKrasnik** [LibertyDSNP/dsnp-wallet-swift#93]
addPublicKeyToMsa function from ExtrinsicManager returns 'unknown' result during execution. 

Expected result: MSA is added to a new Public key

**Comment by ryansheh** [comment]
Because this costs capacity and will likely be handled by custodial wallet, I'm putting this on hold until it's clear to us that the standalone wallet will need to execute this extrinsic.
